config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "categories#index"
  resources :categories, only:[ :index, :new, :show, :create] do
    resources :dealings, only:[ :new, :create, :destroy]
  end
end


# root GET    /                                                                                                 categories#index
# category_dealings POST   /categories/:category_id/dealings(.:format)                                                       dealings#create
# new_category_dealing GET    /categories/:category_id/dealings/new(.:format)                                                   dealings#new
#  category_dealing DELETE /categories/:category_id/dealings/:id(.:format)                                                   dealings#destroy
#        categories GET    /categories(.:format)                                                                             categories#index
#                   POST   /categories(.:format)                                                                             categories#create
#      new_category GET    /categories/new(.:format)                                                                         categories#new
#          category GET    /categories/:id(.:format)                                                                         categories#show

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_dealings, dependent: :destroy
  has_many :dealings, through: :category_dealings

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_dealing.rb
class CategoryDealing < ApplicationRecord
  belongs_to :category
  belongs_to :dealing
end

app/models/dealing.rb
class Dealing < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_dealings, dependent: :destroy
  has_many :categories, through: :category_dealings

  validates :name, presence: true
  validates :amount, presence: true, comparison: { greater_than: 0 }, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :dealings

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where(author: current_user).includes(:category_dealings).order(created_at: :desc)
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.html { render :new, locals: { category: @category } }
    end
  end

  def create
    @category = Category.new(category_params)
    @category.author = current_user
    if @category.save
      redirect_to root_path(@category), notice: 'Category Added successfully'
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_dealings = @category.dealings.order(created_at: :desc)
    @total = @category_dealings.sum(:amount)
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/dealings_controller.rb
class DealingsController < ApplicationController
  def new
    @dealing = Dealing.new
    @categories = Category.where(author: current_user)
  end

  def create
    @dealing = Dealing.new(dealing_params)
    @dealing.author = current_user
    if @dealing.save
      @cd = CategoryDealing.create(dealing_id: @dealing.id, category_id: params[:category])
      redirect_to category_path(@cd.category), notice: 'Transaction Added Successfuly'
    else
      render :new
    end
  end

  def destroy
    @dealings = Dealing.find(prams[:id])
    @dealings.destroy
    redirect_to category_path(id: params[:category_id]), alert: 'Transaction deleted successfully'
  end

  private

  def dealing_params
    params.require(:dealing).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<nav class="navbar">
<li class="nav_head">
  <i class="fa-sharp fa-solid fa-bars"></i>
    <h3>Categories</h3>
  <i class="fa-solid fa-magnifying-glass"></i>
</li>

<%= render "shared/navbar" %>
</nav>
<%= render "shared/flash"%>
<ul class="category_container">
  <h2>Categories</h2>
  <%if @categories.empty? %>
    <h3 class="empty">No Content Added</h3>
    <% else %>
  <%@categories.each do |category| %>
  <%= render "shared/catalog_card", catalog: category %>
  <% end %>
  <div>
  <% end %>
  <%= link_to "New Category", new_category_path, class: "link_btn" %>
  </div>
</ul>

app/views/categories/new.html.erb
<h1>Categories New Page</h1>

<div class="form__container">
<h2>New Category</h2>

<%= form_with model: @category, url: categories_path, method: :post, data: { turbo: false } do |f| %>
    <div class="form__control">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="form__control">
      <%= f.label :icon%><br />
      <%= f.text_field :icon %>
    </div>
    <div class="back">
    <%=link_to root_path, class: "back_home" do %>
      <span>Back</span>
    <% end %>
    </div>

    <%= f.submit "Save", class: "link_btn"%>
<% end %>
  </div>

app/views/categories/show.html.erb
<h1>Categories Show Page</h1>
<nav class="navbar">
  <li class="nav_head">
    <% link_to category_dealings_path(@category) do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
      <h3>Transactions</h3>
    <i class="fa-solid fa-magnifying-glass"></i>
  </li>
  <%= render "shared/navbar" %>
</nav>

<%= render "shared/flash" %>
<div class="show-btn">
  <%= link_to "Back", root_path( @category), class: "back_btn"%>

  <%= link_to "Add", new_category_dealing_path( @category), class: "Add_btn"%>
</div>
<div class="deal_container">
  <%= render "shared/catalog_card", catalog: @category %>

  <hr/>

  <% if @category_dealings.empty?%>
    <h3 class="zero_content"> No Content Added </h3>
  <% else %>
  
    <% @category_dealings.each do |c| %>
  <li class="catalog_list">
    <div class="catolog_content">
      <div class="created_at">
        <p class="hour"><%= c.created_at.strftime("%h")%></p>
        <p class="day"><%= c.created_at.strftime("%d")%></p>
        <p class="year hour"><%= c.created_at.strftime("%y")%></p>
      </div>
      <div class="data">
      <div class="name-time">
        <%= c.name %>
        <span><%= c.created_at.strftime("%T")%>
        <%= c.created_at.strftime("%p")%>
        </span>

      </div>  
        <p class="time">
          <span>
          </span>
        </p>
          <span>Amount: <%= c.amount %></span>
      </div>
    </div>

    
  </li>  

  <% end %>
  <p class="total">Total Payment: $<%= @total.floor(2) %></p>
  <% end%>
  <%= link_to "New Transaction", new_category_dealing_path( @category), class: "link_btn"%>

</div>

app/views/dealings/index.html.erb
<h1>Hello Dealings Index<h1>

app/views/dealings/new.html.erb
<h1> Dealings New Page</h1>

<div class="form">
  <h2> New Transaction</h2>

  <%= form_with model: @dealing, url: category_dealings_path(:category_id) do |f| %>
    <div class="form__control">
      <%=f.label :name%> <br>
      <%= f.text_field :name %>
    </div>

    <div class="form__control">
      <%= f.label :amount %> <br>
      <%= f.text_field :amount, step: :any %>
    </div>

    <div class="form__control">
      <%= f.label :category %>
      <%= select_tag :category, options_for_select(Category.all.map { | category| [category.name, category.id]}), {promt: 'Select Category', required: true} %>
    </div>

    <%= f.submit "Save", class: "link_btn"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_catalog_card.html.erb
<% @total = 0 %>
  <% catalog.category_dealings.each { |u| @total += u.dealing.amount }%>

  <li class="catalog">
    <div class="content">
      <%= image_tag "#{catalog.icon}" %>
      <h3><%= link_to catalog.name, category_path( catalog)%></h3>
    </div>
    <p>Total: $<%= @total.floor %></p>
  </li>

app/views/shared/_flash.html.erb
<%if flash[:notice]%>
  <div class="notice">
    <%= flash[:notice]%>
  </div>
<% end %>

<%if flash[:alert]%>
  <div class="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
 <ul class="nav__menu">
    <% if user_signed_in? %>
      <li class="nav_item">
        <%= link_to current_user.name, edit_user_registration_path %>
      </li>

        <%= button_to destroy_user_session_path , method: :delete do %>
          <i class="fa-solid fa-right-to-bracket">Delete</i>
        <% end %>
      
    <% end %>
  </ul>